2018-02-16 00:10:38.715 [error] <0.539.0>@log:error:15 {validate} error reason {badmatch,<<"html>">>}
2018-02-16 00:10:43.779 [error] <0.541.0>@log:error:15 {validate} error reason {badmatch,<<"html>">>}
2018-02-16 10:33:10.593 [error] <0.535.0> CRASH REPORT Process <0.535.0> with 0 neighbours crashed with reason: {error,{invalid_ejson,{error,{invalid_ejson,{<<"catalog">>,[],[{<<"book">>,[{<<"id">>,<<"bk101">>}],[{<<"author">>,[],[<<"Gambardella, Matthew">>]},{<<"title">>,[],[<<"XML Developer's Guide">>]},{<<"genre">>,[],[<<"Computer">>]},{<<"price">>,[],[<<"44.95">>]},{<<"publish_date">>,[],[<<"2000-10-01">>]},{<<"description">>,[],[<<"An in-depth look at creating applications \n      with XML.">>]}]},{<<"book">>,[{<<"id">>,<<"bk102">>}],[{<<"author">>,[],[<<"Ralls, Kim">>]},{<<"title">>,[],[<<"Midnigh...">>]},...]},...]}}}}} in jiffy:encode/2 line 98
2018-02-16 10:33:10.596 [error] <0.476.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.534.0>,1,<0.535.0>,{nocatch,{error,{invalid_ejson,{error,{invalid_ejson,{<<"catalog">>,[],[{<<"book">>,[{<<"id">>,<<"bk101">>}],[{<<"author">>,[],[<<"Gambardella, Matthew">>]},{<<"title">>,[],[<<"XML Developer's Guide">>]},{<<"genre">>,[],[<<"Computer">>]},{<<"price">>,[],[<<"44.95">>]},{<<"publish_date">>,[],[<<"2000-10-01">>]},{<<"description">>,[],[<<"An in-depth look at creating applications \n      with XML.">>]}]},{<<"book">>,[{<<"id">>,<<"bk102">>}],[{<<"...">>,...},...]},...]}}}}}},...]},...}}
2018-02-16 11:08:18.850 [error] <0.553.0>@log:error:15 {validate} error reason {badmatch,<<"html>">>}
2018-02-16 11:25:30.401 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours crashed with reason: {error,{invalid_ejson,{<<"html">>,[],[{<<"head">>,[],[{<<"title">>,[],[<<"A Simple HTML Document">>]}]},{<<"body">>,[],[{<<"p">>,[],[<<"This is a very simple HTML document">>]},{<<"p">>,[],[<<"It only has two paragraphs">>]}]}]}}} in jiffy:encode/2 line 98
2018-02-16 11:25:30.402 [error] <0.487.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.546.0>,1,<0.547.0>,{nocatch,{error,{invalid_ejson,{<<"html">>,[],[{<<"head">>,[],[{<<"title">>,[],[<<"A Simple HTML Document">>]}]},{<<"body">>,[],[{<<"p">>,[],[<<"This is a very simple HTML document">>]},{<<"p">>,[],[<<"It only has two paragraphs">>]}]}]}}}},[{jiffy,encode,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jiffy/src/jiffy.erl"},{line,98}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/defaul..."},...]},...]]},...}}
2018-02-16 11:29:38.075 [error] <0.542.0>@log:error:15 {validate} {badmatch,<<"title>\n</head>\n\n<body>\n<p>This is a very simple HTML document</p>\n<p>It only has two paragraphs</p>\n</body>\n</html>">>}
2018-02-16 11:52:59.150 [error] <0.540.0>@db_sup:init:20 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no match of right hand value undefined in db_sup:init/1 line 20
2018-02-16 11:52:59.150 [error] <0.539.0>@db_sup:init:20 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no match of right hand value undefined in db_sup:init/1 line 20 in context start_error
2018-02-16 11:52:59.150 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{{badmatch,undefined},[{db_sup,init,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/db/db_sup.erl"},{line,20}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{test_project_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-02-16 12:00:18.194 [error] <0.540.0>@db_sup:init:20 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no match of right hand value undefined in db_sup:init/1 line 20
2018-02-16 12:00:18.194 [error] <0.539.0>@db_sup:init:20 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no match of right hand value undefined in db_sup:init/1 line 20 in context start_error
2018-02-16 12:00:18.194 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{{badmatch,undefined},[{db_sup,init,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/db/db_sup.erl"},{line,20}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{test_project_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-02-16 12:01:48.136 [error] <0.545.0> gen_server <0.545.0> terminated with reason: nxdomain
2018-02-16 12:01:48.136 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 1 neighbours exited with reason: nxdomain in gen_server:handle_common_reply/8 line 726
2018-02-16 12:01:54.368 [error] <0.550.0> gen_server <0.550.0> terminated with reason: nxdomain
2018-02-16 12:01:54.368 [error] <0.550.0> CRASH REPORT Process <0.550.0> with 1 neighbours exited with reason: nxdomain in gen_server:handle_common_reply/8 line 726
2018-02-16 12:02:43.308 [error] <0.553.0> gen_server <0.553.0> terminated with reason: nxdomain
2018-02-16 12:02:43.309 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: nxdomain in gen_server:handle_common_reply/8 line 726
2018-02-16 12:04:33.475 [error] <0.541.0>@poolboy:new_worker:275 CRASH REPORT Process <0.541.0> with 0 neighbours crashed with reason: no match of right hand value {error,{'EXIT',{undef,[{db_worker,start_link,[[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in poolboy:new_worker/1 line 275
2018-02-16 12:04:33.475 [error] <0.540.0>@poolboy:new_worker:275 Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{'EXIT',{undef,[{db_worker,start_link,[[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in poolboy:new_worker/1 line 275 in context start_error
2018-02-16 12:04:33.476 [error] <0.542.0>@poolboy:new_worker:275 gen_server <0.542.0> terminated with reason: no match of right hand value {error,{'EXIT',{undef,[{db_worker,start_link,[[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in poolboy:new_worker/1 line 275
2018-02-16 12:04:33.476 [error] <0.542.0>@poolboy:new_worker:275 CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: no match of right hand value {error,{'EXIT',{undef,[{db_worker,start_link,[[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in poolboy:new_worker/1 line 275 in gen_server:decode_msg/9 line 410
2018-02-16 12:04:33.476 [error] <0.539.0> Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,pool,{{badmatch,{error,{'EXIT',{undef,[{db_worker,start_link,[[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.er..."},...]}]}}}},...}}} in context start_error
2018-02-16 12:04:33.476 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{shutdown,{failed_to_start_child,pool,{{badmatch,{error,{'EXIT',{undef,[{db_worker,start_link,[[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,...}]}}}},...}}}}},...} in application_master:init/4 line 134
2018-02-16 12:06:00.666 [error] <0.541.0>@poolboy:new_worker:275 CRASH REPORT Process <0.541.0> with 1 neighbours crashed with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:06:00.667 [error] <0.540.0>@poolboy:new_worker:275 Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context start_error
2018-02-16 12:06:00.667 [error] <0.542.0>@poolboy:new_worker:275 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context shutdown_error
2018-02-16 12:06:00.667 [error] <0.542.0>@poolboy:new_worker:275 gen_server <0.542.0> terminated with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:06:00.667 [error] <0.542.0>@poolboy:new_worker:275 CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in gen_server:decode_msg/9 line 410
2018-02-16 12:06:00.668 [error] <0.539.0> Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,pool,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,145}]},{gen_server,init_it,2,[{file,"ge..."},...]},...]}}} in context start_error
2018-02-16 12:06:00.668 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{shutdown,{failed_to_start_child,pool,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,...}]},...]}}}}},...} in application_master:init/4 line 134
2018-02-16 12:06:20.901 [error] <0.541.0>@poolboy:new_worker:275 CRASH REPORT Process <0.541.0> with 1 neighbours crashed with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:06:20.901 [error] <0.540.0>@poolboy:new_worker:275 Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context start_error
2018-02-16 12:06:20.902 [error] <0.539.0> Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,pool,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,145}]},{gen_server,init_it,2,[{file,"ge..."},...]},...]}}} in context start_error
2018-02-16 12:06:20.902 [error] <0.542.0>@poolboy:new_worker:275 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context shutdown_error
2018-02-16 12:06:20.902 [error] <0.542.0>@poolboy:new_worker:275 gen_server <0.542.0> terminated with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:06:20.902 [error] <0.542.0>@poolboy:new_worker:275 CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in gen_server:decode_msg/9 line 410
2018-02-16 12:06:20.902 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{shutdown,{failed_to_start_child,pool,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,...}]},...]}}}}},...} in application_master:init/4 line 134
2018-02-16 12:08:34.884 [error] <0.546.0>@log:error:15 {validate} {badmatch,<<"title>\n</head>\n\n<body>\n<p>This is a very simple HTML document</p>\n<p>It only has two paragraphs</p>\n</body>\n</html>">>}
2018-02-16 12:09:03.207 [error] <0.541.0>@poolboy:new_worker:275 CRASH REPORT Process <0.541.0> with 1 neighbours crashed with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:09:03.208 [error] <0.540.0>@poolboy:new_worker:275 Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context start_error
2018-02-16 12:09:03.208 [error] <0.542.0>@poolboy:new_worker:275 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context shutdown_error
2018-02-16 12:09:03.208 [error] <0.542.0>@poolboy:new_worker:275 gen_server <0.542.0> terminated with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:09:03.208 [error] <0.542.0>@poolboy:new_worker:275 CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in gen_server:decode_msg/9 line 410
2018-02-16 12:09:03.208 [error] <0.539.0> Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,pool,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,145}]},{gen_server,init_it,2,[{file,"ge..."},...]},...]}}} in context start_error
2018-02-16 12:09:03.208 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{shutdown,{failed_to_start_child,pool,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,...}]},...]}}}}},...} in application_master:init/4 line 134
2018-02-16 12:11:06.708 [error] <0.541.0>@poolboy:new_worker:275 CRASH REPORT Process <0.541.0> with 1 neighbours crashed with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:11:06.709 [error] <0.540.0>@poolboy:new_worker:275 Supervisor db_sup had child pool1 started with poolboy:start_link([{name,{local,pool1}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context start_error
2018-02-16 12:11:06.709 [error] <0.542.0>@poolboy:new_worker:275 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in context shutdown_error
2018-02-16 12:11:06.709 [error] <0.542.0>@poolboy:new_worker:275 gen_server <0.542.0> terminated with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275
2018-02-16 12:11:06.710 [error] <0.542.0>@poolboy:new_worker:275 CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: no match of right hand value {error,{already_started,<0.543.0>}} in poolboy:new_worker/1 line 275 in gen_server:decode_msg/9 line 410
2018-02-16 12:11:06.710 [error] <0.539.0> Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,pool1,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,145}]},{gen_server,init_it,2,[{file,"g..."},...]},...]}}} in context start_error
2018-02-16 12:11:06.710 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{shutdown,{failed_to_start_child,pool1,{{badmatch,{error,{already_started,<0.543.0>}}},[{poolboy,new_worker,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,275}]},{poolboy,prepopulate,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,296}]},{poolboy,init,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/poolboy/src/poolboy.erl"},{line,...}]},...]}}}}},...} in application_master:init/4 line 134
2018-02-16 12:20:47.174 [error] <0.543.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.544.0>,#Ref<0.1376464387.4110417924.197601>}}} - 
2018-02-16 12:20:47.174 [error] <0.549.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.550.0>,#Ref<0.1376464387.4110417924.197647>}}} - 
2018-02-16 12:20:47.174 [error] <0.553.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.554.0>,#Ref<0.1376464387.4110417924.197693>}}} - 
2018-02-16 12:20:47.174 [error] <0.547.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.548.0>,#Ref<0.1376464387.4110417924.197624>}}} - 
2018-02-16 12:20:47.174 [error] <0.551.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.552.0>,#Ref<0.1376464387.4110417924.197670>}}} - 
2018-02-16 12:20:47.175 [error] <0.557.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.558.0>,#Ref<0.1376464387.4110417924.197739>}}} - 
2018-02-16 12:20:47.175 [error] <0.563.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.564.0>,#Ref<0.1376464387.4110417924.197808>}}} - 
2018-02-16 12:20:47.175 [error] <0.561.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.562.0>,#Ref<0.1376464387.4110417924.197785>}}} - 
2018-02-16 12:20:47.175 [error] <0.559.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.560.0>,#Ref<0.1376464387.4110417924.197762>}}} - 
2018-02-16 12:20:47.175 [error] <0.555.0>@log:error:15 {db_worker} terminate reason {bad_return_value,{stop,{state,<0.556.0>,#Ref<0.1376464387.4110417924.197716>}}} - 
2018-02-16 12:20:47.175 [error] <0.543.0> gen_server <0.543.0> terminated with reason: bad return value: {stop,{state,<0.544.0>,#Ref<0.1376464387.4110417924.197601>}}
2018-02-16 12:20:47.175 [error] <0.543.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.543.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.544.0>,#Ref<0.1376464387.4110417924.197601>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.176 [error] <0.549.0> gen_server <0.549.0> terminated with reason: bad return value: {stop,{state,<0.550.0>,#Ref<0.1376464387.4110417924.197647>}}
2018-02-16 12:20:47.176 [error] <0.549.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.549.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.550.0>,#Ref<0.1376464387.4110417924.197647>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.176 [error] <0.553.0> gen_server <0.553.0> terminated with reason: bad return value: {stop,{state,<0.554.0>,#Ref<0.1376464387.4110417924.197693>}}
2018-02-16 12:20:47.176 [error] <0.553.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.554.0>,#Ref<0.1376464387.4110417924.197693>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.181 [error] <0.547.0> gen_server <0.547.0> terminated with reason: bad return value: {stop,{state,<0.548.0>,#Ref<0.1376464387.4110417924.197624>}}
2018-02-16 12:20:47.181 [error] <0.547.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.547.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.548.0>,#Ref<0.1376464387.4110417924.197624>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.181 [error] <0.551.0> gen_server <0.551.0> terminated with reason: bad return value: {stop,{state,<0.552.0>,#Ref<0.1376464387.4110417924.197670>}}
2018-02-16 12:20:47.181 [error] <0.551.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.551.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.552.0>,#Ref<0.1376464387.4110417924.197670>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.181 [error] <0.557.0> gen_server <0.557.0> terminated with reason: bad return value: {stop,{state,<0.558.0>,#Ref<0.1376464387.4110417924.197739>}}
2018-02-16 12:20:47.181 [error] <0.557.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.558.0>,#Ref<0.1376464387.4110417924.197739>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.181 [error] <0.563.0> gen_server <0.563.0> terminated with reason: bad return value: {stop,{state,<0.564.0>,#Ref<0.1376464387.4110417924.197808>}}
2018-02-16 12:20:47.181 [error] <0.563.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.563.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.564.0>,#Ref<0.1376464387.4110417924.197808>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.182 [error] <0.561.0> gen_server <0.561.0> terminated with reason: bad return value: {stop,{state,<0.562.0>,#Ref<0.1376464387.4110417924.197785>}}
2018-02-16 12:20:47.182 [error] <0.561.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.561.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.562.0>,#Ref<0.1376464387.4110417924.197785>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.182 [error] <0.559.0> gen_server <0.559.0> terminated with reason: bad return value: {stop,{state,<0.560.0>,#Ref<0.1376464387.4110417924.197762>}}
2018-02-16 12:20:47.182 [error] <0.555.0> gen_server <0.555.0> terminated with reason: bad return value: {stop,{state,<0.556.0>,#Ref<0.1376464387.4110417924.197716>}}
2018-02-16 12:20:47.182 [error] <0.555.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.555.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.556.0>,#Ref<0.1376464387.4110417924.197716>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.182 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:20:47.182 [error] <0.559.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.559.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.560.0>,#Ref<0.1376464387.4110417924.197762>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:20:47.182 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.550.0>,#Ref<0.1376464387.4110417924.197647>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.548.0>,#Ref<0.1376464387.4110417924.197624>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.564.0>,#Ref<0.1376464387.4110417924.197808>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.558.0>,#Ref<0.1376464387.4110417924.197739>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.544.0>,#Ref<0.1376464387.4110417924.197601>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.552.0>,#Ref<0.1376464387.4110417924.197670>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.560.0>,#Ref<0.1376464387.4110417924.197762>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.554.0>,#Ref<0.1376464387.4110417924.197693>}} in context shutdown_error
2018-02-16 12:20:47.183 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.562.0>,#Ref<0.1376464387.4110417924.197785>}} in context shutdown_error
2018-02-16 12:20:47.184 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.556.0>,#Ref<0.1376464387.4110417924.197716>}} in context shutdown_error
2018-02-16 12:20:47.184 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:20:47.184 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:22:45.088 [error] <0.549.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.557.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.547.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.543.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.555.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.553.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.551.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.563.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.561.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.559.0>@log:error:15 {db_worker} terminate reason shutdown - 
2018-02-16 12:22:45.089 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:22:45.089 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:22:45.089 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:23:26.617 [error] <0.570.0>@log:error:15 {validate} {badmatch,<<"title>\n</head>\n\n<body>\n<p>This is a very simple HTML document</p>\n<p>It only has two paragraphs</p>\n</body>\n</html>">>}
2018-02-16 12:23:33.932 [error] <0.557.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.555.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.553.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.551.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.563.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.547.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.549.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.561.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.543.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.559.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:23:33.932 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:23:33.933 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:23:33.933 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:24:26.963 [error] <0.549.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.963 [error] <0.553.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.963 [error] <0.551.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.963 [error] <0.547.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.964 [error] <0.557.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.964 [error] <0.561.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.964 [error] <0.559.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.964 [error] <0.563.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.964 [error] <0.543.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.964 [error] <0.555.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:24:26.964 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:24:26.964 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:24:26.964 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:25:38.994 [error] <0.543.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.994 [error] <0.549.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.994 [error] <0.549.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.994 [error] <0.553.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.994 [error] <0.553.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.994 [error] <0.551.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.994 [error] <0.551.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.994 [error] <0.547.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.995 [error] <0.547.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.995 [error] <0.557.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.995 [error] <0.563.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.995 [error] <0.557.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.995 [error] <0.563.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.995 [error] <0.561.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.995 [error] <0.559.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.995 [error] <0.561.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.995 [error] <0.559.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.995 [error] <0.555.0>@log:error:15 {db_worker} info - {'EXIT',<0.541.0>,killed}
2018-02-16 12:25:38.995 [error] <0.555.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.995 [error] <0.543.0>@log:error:15 {db_worker} terminate reason - shutdown
2018-02-16 12:25:38.996 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:25:38.997 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:25:38.997 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:27:41.375 [error] <0.543.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.375 [error] <0.543.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.544.0>,#Ref<0.2641453909.2232680449.119983>}}}
2018-02-16 12:27:41.375 [error] <0.549.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.375 [error] <0.549.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.550.0>,#Ref<0.2641453909.2232680449.120031>}}}
2018-02-16 12:27:41.375 [error] <0.553.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.553.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.554.0>,#Ref<0.2641453909.2232680449.120079>}}}
2018-02-16 12:27:41.376 [error] <0.551.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.551.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.552.0>,#Ref<0.2641453909.2232680449.120055>}}}
2018-02-16 12:27:41.376 [error] <0.547.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.547.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.548.0>,#Ref<0.2641453909.2232680449.120007>}}}
2018-02-16 12:27:41.376 [error] <0.557.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.557.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.558.0>,#Ref<0.2641453909.2232680449.120127>}}}
2018-02-16 12:27:41.376 [error] <0.563.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.563.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.564.0>,#Ref<0.2641453909.2232680449.120199>}}}
2018-02-16 12:27:41.376 [error] <0.561.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.561.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.562.0>,#Ref<0.2641453909.2232680449.120175>}}}
2018-02-16 12:27:41.376 [error] <0.559.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.559.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.560.0>,#Ref<0.2641453909.2232680449.120151>}}}
2018-02-16 12:27:41.376 [error] <0.555.0>@log:error:15 {db_worker} exit pid - <0.541.0> reason - killed
2018-02-16 12:27:41.376 [error] <0.555.0>@log:error:15 {db_worker} terminate reason - {bad_return_value,{stop,{state,<0.556.0>,#Ref<0.2641453909.2232680449.120103>}}}
2018-02-16 12:27:41.377 [error] <0.543.0> gen_server <0.543.0> terminated with reason: bad return value: {stop,{state,<0.544.0>,#Ref<0.2641453909.2232680449.119983>}}
2018-02-16 12:27:41.377 [error] <0.543.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.543.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.544.0>,#Ref<0.2641453909.2232680449.119983>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.377 [error] <0.549.0> gen_server <0.549.0> terminated with reason: bad return value: {stop,{state,<0.550.0>,#Ref<0.2641453909.2232680449.120031>}}
2018-02-16 12:27:41.377 [error] <0.549.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.549.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.550.0>,#Ref<0.2641453909.2232680449.120031>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.377 [error] <0.553.0> gen_server <0.553.0> terminated with reason: bad return value: {stop,{state,<0.554.0>,#Ref<0.2641453909.2232680449.120079>}}
2018-02-16 12:27:41.377 [error] <0.553.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.554.0>,#Ref<0.2641453909.2232680449.120079>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.378 [error] <0.551.0> gen_server <0.551.0> terminated with reason: bad return value: {stop,{state,<0.552.0>,#Ref<0.2641453909.2232680449.120055>}}
2018-02-16 12:27:41.378 [error] <0.551.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.551.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.552.0>,#Ref<0.2641453909.2232680449.120055>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.378 [error] <0.547.0> gen_server <0.547.0> terminated with reason: bad return value: {stop,{state,<0.548.0>,#Ref<0.2641453909.2232680449.120007>}}
2018-02-16 12:27:41.378 [error] <0.547.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.547.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.548.0>,#Ref<0.2641453909.2232680449.120007>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.378 [error] <0.557.0> gen_server <0.557.0> terminated with reason: bad return value: {stop,{state,<0.558.0>,#Ref<0.2641453909.2232680449.120127>}}
2018-02-16 12:27:41.378 [error] <0.557.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.558.0>,#Ref<0.2641453909.2232680449.120127>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.379 [error] <0.563.0> gen_server <0.563.0> terminated with reason: bad return value: {stop,{state,<0.564.0>,#Ref<0.2641453909.2232680449.120199>}}
2018-02-16 12:27:41.379 [error] <0.563.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.563.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.564.0>,#Ref<0.2641453909.2232680449.120199>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.379 [error] <0.561.0> gen_server <0.561.0> terminated with reason: bad return value: {stop,{state,<0.562.0>,#Ref<0.2641453909.2232680449.120175>}}
2018-02-16 12:27:41.379 [error] <0.561.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.561.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.562.0>,#Ref<0.2641453909.2232680449.120175>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.379 [error] <0.559.0> gen_server <0.559.0> terminated with reason: bad return value: {stop,{state,<0.560.0>,#Ref<0.2641453909.2232680449.120151>}}
2018-02-16 12:27:41.379 [error] <0.559.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.559.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.560.0>,#Ref<0.2641453909.2232680449.120151>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.379 [error] <0.555.0> gen_server <0.555.0> terminated with reason: bad return value: {stop,{state,<0.556.0>,#Ref<0.2641453909.2232680449.120103>}}
2018-02-16 12:27:41.379 [error] <0.555.0>@gen_server:handle_common_reply:730 CRASH REPORT Process <0.555.0> with 1 neighbours exited with reason: bad return value: {stop,{state,<0.556.0>,#Ref<0.2641453909.2232680449.120103>}} in gen_server:handle_common_reply/8 line 730
2018-02-16 12:27:41.380 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:27:41.380 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.548.0>,#Ref<0.2641453909.2232680449.120007>}} in context shutdown_error
2018-02-16 12:27:41.380 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.558.0>,#Ref<0.2641453909.2232680449.120127>}} in context shutdown_error
2018-02-16 12:27:41.380 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.556.0>,#Ref<0.2641453909.2232680449.120103>}} in context shutdown_error
2018-02-16 12:27:41.380 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.554.0>,#Ref<0.2641453909.2232680449.120079>}} in context shutdown_error
2018-02-16 12:27:41.381 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.564.0>,#Ref<0.2641453909.2232680449.120199>}} in context shutdown_error
2018-02-16 12:27:41.381 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.544.0>,#Ref<0.2641453909.2232680449.119983>}} in context shutdown_error
2018-02-16 12:27:41.381 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.552.0>,#Ref<0.2641453909.2232680449.120055>}} in context shutdown_error
2018-02-16 12:27:41.381 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.562.0>,#Ref<0.2641453909.2232680449.120175>}} in context shutdown_error
2018-02-16 12:27:41.382 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.550.0>,#Ref<0.2641453909.2232680449.120031>}} in context shutdown_error
2018-02-16 12:27:41.382 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason bad return value: {stop,{state,<0.560.0>,#Ref<0.2641453909.2232680449.120151>}} in context shutdown_error
2018-02-16 12:27:41.382 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:27:41.382 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:29:45.743 [error] <0.543.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.743 [error] <0.543.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.743 [error] <0.549.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.743 [error] <0.549.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.743 [error] <0.547.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.743 [error] <0.547.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.743 [error] <0.553.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.744 [error] <0.553.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.744 [error] <0.551.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.744 [error] <0.557.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.744 [error] <0.551.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.744 [error] <0.557.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.744 [error] <0.543.0> gen_server <0.543.0> terminated with reason: killed
2018-02-16 12:29:45.744 [error] <0.563.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.744 [error] <0.549.0> gen_server <0.549.0> terminated with reason: killed
2018-02-16 12:29:45.744 [error] <0.563.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.744 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.744 [error] <0.561.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.744 [error] <0.561.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.744 [error] <0.559.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.745 [error] <0.559.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.745 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.745 [error] <0.547.0> gen_server <0.547.0> terminated with reason: killed
2018-02-16 12:29:45.745 [error] <0.553.0> gen_server <0.553.0> terminated with reason: killed
2018-02-16 12:29:45.745 [error] <0.555.0>@log:error:15 {db_worker_handle_info} exit pid - <0.541.0> reason - killed
2018-02-16 12:29:45.745 [error] <0.555.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:29:45.745 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.745 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.745 [error] <0.551.0> gen_server <0.551.0> terminated with reason: killed
2018-02-16 12:29:45.745 [error] <0.557.0> gen_server <0.557.0> terminated with reason: killed
2018-02-16 12:29:45.745 [error] <0.551.0> CRASH REPORT Process <0.551.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.746 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:29:45.746 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.746 [error] <0.563.0> gen_server <0.563.0> terminated with reason: killed
2018-02-16 12:29:45.746 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.746 [error] <0.561.0> gen_server <0.561.0> terminated with reason: killed
2018-02-16 12:29:45.746 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.746 [error] <0.559.0> gen_server <0.559.0> terminated with reason: killed
2018-02-16 12:29:45.746 [error] <0.559.0> CRASH REPORT Process <0.559.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.746 [error] <0.555.0> gen_server <0.555.0> terminated with reason: killed
2018-02-16 12:29:45.747 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:29:45.747 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason killed in context shutdown_error
2018-02-16 12:29:45.747 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:29:45.747 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:30:32.021 [error] <0.570.0>@log:error:15 {validate} {badmatch,<<"title>\n</head>\n\n<body>\n<p>This is a very simple HTML document</p>\n<p>It only has two paragraphs</p>\n</body>\n</html>">>}
2018-02-16 12:30:34.760 [error] <0.543.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.549.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.553.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.551.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.547.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.557.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.563.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.559.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.561.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.760 [error] <0.555.0>@log:error:15 {db_worker_terminate} reason - killed
2018-02-16 12:30:34.761 [error] <0.543.0> gen_server <0.543.0> terminated with reason: killed
2018-02-16 12:30:34.761 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.761 [error] <0.549.0> gen_server <0.549.0> terminated with reason: killed
2018-02-16 12:30:34.761 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.761 [error] <0.553.0> gen_server <0.553.0> terminated with reason: killed
2018-02-16 12:30:34.761 [error] <0.551.0> gen_server <0.551.0> terminated with reason: killed
2018-02-16 12:30:34.764 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.765 [error] <0.551.0> CRASH REPORT Process <0.551.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.765 [error] <0.547.0> gen_server <0.547.0> terminated with reason: killed
2018-02-16 12:30:34.765 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.766 [error] <0.557.0> gen_server <0.557.0> terminated with reason: killed
2018-02-16 12:30:34.766 [error] <0.563.0> gen_server <0.563.0> terminated with reason: killed
2018-02-16 12:30:34.766 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.766 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.766 [error] <0.559.0> gen_server <0.559.0> terminated with reason: killed
2018-02-16 12:30:34.766 [error] <0.561.0> gen_server <0.561.0> terminated with reason: killed
2018-02-16 12:30:34.766 [error] <0.559.0> CRASH REPORT Process <0.559.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.766 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.766 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:30:34.766 [error] <0.555.0> gen_server <0.555.0> terminated with reason: killed
2018-02-16 12:30:34.766 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:30:34.766 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason killed in context shutdown_error
2018-02-16 12:30:34.767 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:30:34.767 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:32:39.581 [error] <0.543.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.581 [error] <0.543.0> gen_server <0.543.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.581 [error] <0.549.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.581 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.581 [error] <0.549.0> gen_server <0.549.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.581 [error] <0.553.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.581 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.581 [error] <0.551.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.581 [error] <0.553.0> gen_server <0.553.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.581 [error] <0.557.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.581 [error] <0.547.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.582 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.582 [error] <0.563.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.582 [error] <0.561.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.582 [error] <0.559.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.582 [error] <0.551.0> gen_server <0.551.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.582 [error] <0.555.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:32:39.582 [error] <0.551.0> CRASH REPORT Process <0.551.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.582 [error] <0.557.0> gen_server <0.557.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.582 [error] <0.547.0> gen_server <0.547.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.582 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.582 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.582 [error] <0.563.0> gen_server <0.563.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.582 [error] <0.561.0> gen_server <0.561.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.582 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.582 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.583 [error] <0.559.0> gen_server <0.559.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.583 [error] <0.559.0> CRASH REPORT Process <0.559.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.583 [error] <0.555.0> gen_server <0.555.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:32:39.583 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:32:39.583 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:32:39.583 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason {<0.541.0>,killed} in context shutdown_error
2018-02-16 12:32:39.583 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:32:39.583 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:36:31.862 [error] <0.543.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.862 [error] <0.543.0> gen_server <0.543.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.862 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.862 [error] <0.549.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.862 [error] <0.553.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.862 [error] <0.549.0> gen_server <0.549.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.862 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.862 [error] <0.551.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.862 [error] <0.553.0> gen_server <0.553.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.862 [error] <0.557.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.862 [error] <0.547.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.862 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.863 [error] <0.561.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.863 [error] <0.563.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.863 [error] <0.551.0> gen_server <0.551.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.863 [error] <0.559.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.863 [error] <0.555.0>@log:error:15 {db_worker_terminate} pid <0.541.0> reason - killed
2018-02-16 12:36:31.863 [error] <0.551.0> CRASH REPORT Process <0.551.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.863 [error] <0.547.0> gen_server <0.547.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.863 [error] <0.557.0> gen_server <0.557.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.863 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.863 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.863 [error] <0.561.0> gen_server <0.561.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.863 [error] <0.563.0> gen_server <0.563.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.864 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.864 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.864 [error] <0.559.0> gen_server <0.559.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.864 [error] <0.555.0> gen_server <0.555.0> terminated with reason: {<0.541.0>,killed}
2018-02-16 12:36:31.864 [error] <0.559.0> CRASH REPORT Process <0.559.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.864 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:36:31.864 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 1 neighbours exited with reason: {<0.541.0>,killed} in gen_server:handle_common_reply/8 line 726
2018-02-16 12:36:31.864 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason {<0.541.0>,killed} in context shutdown_error
2018-02-16 12:36:31.864 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:36:31.864 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 12:38:08.299 [error] <0.543.0> gen_server <0.543.0> terminated with reason: killed
2018-02-16 12:38:08.299 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.299 [error] <0.549.0> gen_server <0.549.0> terminated with reason: killed
2018-02-16 12:38:08.299 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.299 [error] <0.553.0> gen_server <0.553.0> terminated with reason: killed
2018-02-16 12:38:08.300 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.300 [error] <0.551.0> gen_server <0.551.0> terminated with reason: killed
2018-02-16 12:38:08.300 [error] <0.551.0> CRASH REPORT Process <0.551.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.300 [error] <0.547.0> gen_server <0.547.0> terminated with reason: killed
2018-02-16 12:38:08.300 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.300 [error] <0.557.0> gen_server <0.557.0> terminated with reason: killed
2018-02-16 12:38:08.301 [error] <0.557.0> CRASH REPORT Process <0.557.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.301 [error] <0.563.0> gen_server <0.563.0> terminated with reason: killed
2018-02-16 12:38:08.301 [error] <0.563.0> CRASH REPORT Process <0.563.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.301 [error] <0.561.0> gen_server <0.561.0> terminated with reason: killed
2018-02-16 12:38:08.301 [error] <0.559.0> gen_server <0.559.0> terminated with reason: killed
2018-02-16 12:38:08.301 [error] <0.561.0> CRASH REPORT Process <0.561.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.301 [error] <0.559.0> CRASH REPORT Process <0.559.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.301 [error] <0.555.0> gen_server <0.555.0> terminated with reason: killed
2018-02-16 12:38:08.301 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 1 neighbours exited with reason: killed in gen_server:handle_common_reply/8 line 726
2018-02-16 12:38:08.302 [error] <0.540.0> Supervisor db_sup had child pool started with poolboy:start_link([{name,{local,pool}},{worker_module,db_worker},{size,10},{max_overflow,20}], [{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at <0.541.0> exit with reason killed in context child_terminated
2018-02-16 12:38:08.302 [error] <0.542.0> Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with db_worker:start_link([{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]) at undefined exit with reason killed in context shutdown_error
2018-02-16 12:38:08.302 [error] <0.542.0> gen_server <0.542.0> terminated with reason: killed
2018-02-16 12:38:08.302 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: killed in gen_server:decode_msg/9 line 410
2018-02-16 13:30:29.291 [error] <0.540.0>@db_sup:init:21 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no match of right hand value undefined in db_sup:init/1 line 21
2018-02-16 13:30:29.291 [error] <0.539.0>@db_sup:init:21 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no match of right hand value undefined in db_sup:init/1 line 21 in context start_error
2018-02-16 13:30:29.291 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{{badmatch,undefined},[{db_sup,init,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/db/db_sup.erl"},{line,21}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{test_project_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-02-16 13:31:08.279 [error] <0.540.0>@db_sup:init:21 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no match of right hand value undefined in db_sup:init/1 line 21
2018-02-16 13:31:08.279 [error] <0.539.0>@db_sup:init:21 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no match of right hand value undefined in db_sup:init/1 line 21 in context start_error
2018-02-16 13:31:08.279 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{{badmatch,undefined},[{db_sup,init,1,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/db/db_sup.erl"},{line,21}]},{supervisor,init,1,[{file,"supervisor.erl"},{line,294}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},{test_project_app,start,[normal,[]]}} in application_master:init/4 line 134
2018-02-16 13:31:43.434 [error] <0.540.0>@supervisor:check_startspec:1295 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,news_db}},{worker_module,undefined},{size,10},{max_overflow,...}],...]},...}, []) line 1295
2018-02-16 13:31:43.434 [error] <0.539.0>@supervisor:check_startspec:1295 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,news_db}},{worker_module,undefined},{size,10},{max_overflow,...}],...]},...}, []) line 1295 in context start_error
2018-02-16 13:31:43.434 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{function_clause,[{supervisor,check_startspec,[{news_db,{poolboy,start_link,[[{name,{local,news_db}},{worker_module,undefined},{size,10},{max_overflow,20}],[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]]},permanent,5000,worker,[poolboy]},[]],[{file,"supervisor.erl"},{line,1295}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,312}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,...},...]}}},...} in application_master:init/4 line 134
2018-02-16 13:32:14.756 [error] <0.540.0>@supervisor:check_startspec:1295 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,news_db}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295
2018-02-16 13:32:14.756 [error] <0.539.0>@supervisor:check_startspec:1295 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,news_db}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295 in context start_error
2018-02-16 13:32:14.756 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{function_clause,[{supervisor,check_startspec,[{news_db,{poolboy,start_link,[[{name,{local,news_db}},{worker_module,db_worker},{size,10},{max_overflow,20}],[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]]},permanent,5000,worker,[poolboy]},[]],[{file,"supervisor.erl"},{line,1295}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,312}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,...},...]}}},...} in application_master:init/4 line 134
2018-02-16 13:33:38.333 [error] <0.540.0>@supervisor:check_startspec:1295 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,db_pool}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295
2018-02-16 13:33:38.334 [error] <0.539.0>@supervisor:check_startspec:1295 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,db_pool}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295 in context start_error
2018-02-16 13:33:38.334 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{function_clause,[{supervisor,check_startspec,[{news_db,{poolboy,start_link,[[{name,{local,db_pool}},{worker_module,db_worker},{size,10},{max_overflow,20}],[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]]},permanent,5000,worker,[poolboy]},[]],[{file,"supervisor.erl"},{line,1295}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,312}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,...},...]}}},...} in application_master:init/4 line 134
2018-02-16 13:34:52.743 [error] <0.540.0>@supervisor:check_startspec:1295 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,db_pools}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295
2018-02-16 13:34:52.743 [error] <0.539.0>@supervisor:check_startspec:1295 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec({news_db,{poolboy,start_link,[[{name,{local,db_pools}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295 in context start_error
2018-02-16 13:34:52.743 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,db_sup,{function_clause,[{supervisor,check_startspec,[{news_db,{poolboy,start_link,[[{name,{local,db_pools}},{worker_module,db_worker},{size,10},{max_overflow,20}],[{hostname,"127.0.0.1"},{database,"vkutovoi"},{username,"vkutovoi"},{password,[]}]]},permanent,5000,worker,[poolboy]},[]],[{file,"supervisor.erl"},{line,1295}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,312}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,...},...]}}},...} in application_master:init/4 line 134
2018-02-16 13:37:42.483 [error] <0.540.0>@supervisor:check_startspec:1295 CRASH REPORT Process <0.540.0> with 0 neighbours crashed with reason: no function clause matching supervisor:check_startspec({db_pools,{poolboy,start_link,[[{name,{local,db_pools}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295
2018-02-16 13:37:42.483 [error] <0.539.0>@supervisor:check_startspec:1295 Supervisor test_project_sup had child db_sup started with db_sup:start_link() at undefined exit with reason no function clause matching supervisor:check_startspec({db_pools,{poolboy,start_link,[[{name,{local,db_pools}},{worker_module,db_worker},{size,10},{max_overflow,...}],...]},...}, []) line 1295 in context start_error
2018-02-16 13:49:06.478 [error] <0.563.0>@lists:zip:387 gen_server <0.563.0> terminated with reason: no function clause matching lists:zip([text], {ok,[{<<"html">>,[{<<"head">>,[{<<"title">>,[{<<"#text">>,<<"A Simple HTML Document">>}]}]},{<<"...">>,...}]}]}) line 387
2018-02-16 13:49:06.478 [error] <0.563.0>@lists:zip:387 CRASH REPORT Process <0.563.0> with 1 neighbours crashed with reason: no function clause matching lists:zip([text], {ok,[{<<"html">>,[{<<"head">>,[{<<"title">>,[{<<"#text">>,<<"A Simple HTML Document">>}]}]},{<<"...">>,...}]}]}) line 387
2018-02-16 13:49:06.478 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 13:49:06.479 [error] <0.542.0>@lists:zip:387 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with {db_worker,start_link,undefined} at <0.563.0> exit with reason no function clause matching lists:zip([text], {ok,[{<<"html">>,[{<<"head">>,[{<<"title">>,[{<<"#text">>,<<"A Simple HTML Document">>}]}]},{<<"...">>,...}]}]}) line 387 in context child_terminated
2018-02-16 13:49:06.479 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 13:50:31.576 [error] <0.563.0>@lists:zip:387 gen_server <0.563.0> terminated with reason: no function clause matching lists:zip([text], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387
2018-02-16 13:50:31.577 [error] <0.563.0>@lists:zip:387 CRASH REPORT Process <0.563.0> with 1 neighbours crashed with reason: no function clause matching lists:zip([text], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387
2018-02-16 13:50:31.577 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 13:50:31.577 [error] <0.542.0>@lists:zip:387 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with {db_worker,start_link,undefined} at <0.563.0> exit with reason no function clause matching lists:zip([text], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387 in context child_terminated
2018-02-16 13:50:31.577 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 13:51:53.457 [error] <0.563.0>@lists:zip:387 gen_server <0.563.0> terminated with reason: no function clause matching lists:zip([], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387
2018-02-16 13:51:53.458 [error] <0.563.0>@lists:zip:387 CRASH REPORT Process <0.563.0> with 1 neighbours crashed with reason: no function clause matching lists:zip([], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387
2018-02-16 13:51:53.458 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 13:51:53.458 [error] <0.542.0>@lists:zip:387 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with {db_worker,start_link,undefined} at <0.563.0> exit with reason no function clause matching lists:zip([], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387 in context child_terminated
2018-02-16 13:51:53.458 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 13:53:36.330 [error] <0.563.0>@lists:zip:387 gen_server <0.563.0> terminated with reason: no function clause matching lists:zip([text], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387
2018-02-16 13:53:36.330 [error] <0.563.0>@lists:zip:387 CRASH REPORT Process <0.563.0> with 1 neighbours crashed with reason: no function clause matching lists:zip([text], <<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a v...">>) line 387
2018-02-16 13:53:36.330 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 13:53:36.330 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:00:02.439 [error] <0.570.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=({\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document\"},{\"#text\":\"It only has two paragraphs\"}]}}}) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 14:00:31.075 [error] <0.572.0>@log:error:15 {db_main_run} cannot insert news {ok,1,[{column,<<"id">>,int4,4,-1,1}],[{9}]}
2018-02-16 14:02:30.822 [error] <0.570.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=({\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document1\"},{\"#text\":\"It only has two paragraphs\"}]}}}) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 14:20:05.046 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:20:05.046 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:20:35.372 [error] <0.573.0>@jsx_parser:value:163 CRASH REPORT Process <0.573.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:20:35.372 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.572.0>,1,<0.573.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:21:27.140 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:21:27.141 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:22:39.621 [error] <0.573.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=({\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document1\"},{\"#text\":\"It only has two paragraphs1\"}]}}}) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 14:23:09.731 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:23:09.731 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:24:48.556 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:24:48.556 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:25:55.761 [error] <0.564.0>@epgsql_binary:encode:58 gen_server <0.564.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:25:55.761 [error] <0.564.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.564.0> with 0 neighbours crashed with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:25:55.761 [error] <0.563.0>@epgsql_binary:encode:58 gen_server <0.563.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:25:55.761 [error] <0.563.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.563.0> with 0 neighbours exited with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:25:55.761 [error] <0.542.0>@epgsql_binary:encode:58 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with {db_worker,start_link,undefined} at <0.563.0> exit with reason bad argument in epgsql_binary:encode/3 line 58 in context child_terminated
2018-02-16 14:25:55.761 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:25:55.761 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:27:47.961 [error] <0.564.0>@epgsql_binary:encode:58 gen_server <0.564.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:27:47.961 [error] <0.564.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.564.0> with 0 neighbours crashed with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:27:47.961 [error] <0.563.0>@epgsql_binary:encode:58 gen_server <0.563.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:27:47.962 [error] <0.563.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.563.0> with 0 neighbours exited with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:27:47.962 [error] <0.542.0>@epgsql_binary:encode:58 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with {db_worker,start_link,undefined} at <0.563.0> exit with reason bad argument in epgsql_binary:encode/3 line 58 in context child_terminated
2018-02-16 14:27:47.962 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:27:47.962 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:33:47.656 [error] <0.572.0>@epgsql_binary:encode:58 gen_server <0.572.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:33:47.656 [error] <0.572.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.572.0> with 0 neighbours crashed with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:33:47.656 [error] <0.571.0>@epgsql_binary:encode:58 gen_server <0.571.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:33:47.656 [error] <0.571.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.571.0> with 0 neighbours exited with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:33:47.657 [error] <0.542.0>@epgsql_binary:encode:58 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with {db_worker,start_link,undefined} at <0.571.0> exit with reason bad argument in epgsql_binary:encode/3 line 58 in context child_terminated
2018-02-16 14:33:47.657 [error] <0.578.0>@jsx_parser:value:163 CRASH REPORT Process <0.578.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 14:33:47.657 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.577.0>,1,<0.578.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 14:34:32.574 [error] <0.580.0>@epgsql_binary:encode:58 gen_server <0.580.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:34:32.574 [error] <0.580.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.580.0> with 0 neighbours crashed with reason: bad argument in epgsql_binary:encode/3 line 58
2018-02-16 14:34:32.576 [error] <0.579.0>@epgsql_binary:encode:58 gen_server <0.579.0> terminated with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:34:32.576 [error] <0.579.0>@epgsql_binary:encode:58 CRASH REPORT Process <0.579.0> with 0 neighbours exited with reason: bad argument in epgsql_binary:encode/3 line 58 in gen_server:call/3 line 214
2018-02-16 14:34:32.576 [error] <0.542.0>@epgsql_binary:encode:58 Supervisor {<0.542.0>,poolboy_sup} had child db_worker started with {db_worker,start_link,undefined} at <0.579.0> exit with reason bad argument in epgsql_binary:encode/3 line 58 in context child_terminated
2018-02-16 14:35:37.108 [error] <0.570.0>@log:error:15 {db_main_run} cannot insert news {ok,1}
2018-02-16 14:36:37.959 [error] <0.574.0>@log:error:15 {db_main_run} cannot update news {ok,0}
2018-02-16 15:21:02.861 [error] <0.570.0>@log:error:15 {db_main_run} cannot update news {ok,[{column,<<"body_news">>,text,-1,-1,1}],[{<<"{\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document123\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document1\"},{\"#text\":\"It only has two paragraphs1\"}]}}}">>}]}
2018-02-16 15:22:51.587 [error] <0.572.0>@log:error:15 {db_main_run} cannot update news {ok,[{column,<<"body_news">>,text,-1,-1,1}],[]}
2018-02-16 15:35:42.917 [error] <0.583.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=({\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document123\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document1\"},{\"#text\":\"It only has two paragraphs1\"}]}}}) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:36:37.248 [error] <0.587.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=({\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document123\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document1\"},{\"#text\":\"It only has two p2aragraphs1\"}]}}}) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:38:20.783 [error] <0.570.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=({\"html\":{\"head\":{\"title\":{\"#text\":\"A Simple HTML Document123\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document1\"},{\"#text\":\"It only has two p2aragraphs1\"}]}}}) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:49:04.291 [error] <0.586.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=({\"html\":{\"head\":{\"title\":{\"#text\":\"select\"}},\"body\":{\"p\":[{\"#text\":\"This is a very simple HTML document1\"},{\"#text\":\"It only has two p2aragraphs1\"}]}}}) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:54:26.887 [error] <0.570.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=(\"ok\") already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:54:54.916 [error] <0.573.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=(\"ok\") already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:54:55.847 [error] <0.574.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=(\"ok\") already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:55:00.046 [error] <0.575.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=(\"ok\") already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 15:55:00.924 [error] <0.576.0>@log:error:15 {db_main_run} cannot insert news {error,{error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"news_body_news_key\"">>,[{constraint_name,<<"news_body_news_key">>},{detail,<<"Key (body_news)=(\"ok\") already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"434">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"public">>},{severity,<<"ERROR">>},{table_name,<<"news">>}]}}
2018-02-16 16:00:48.902 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 16:00:48.903 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 16:01:16.652 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 16:01:16.652 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 16:01:44.207 [error] <0.570.0>@jsx_parser:value:163 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 16:01:44.208 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.569.0>,1,<0.570.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 16:01:50.217 [error] <0.573.0>@jsx_parser:value:163 CRASH REPORT Process <0.573.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 16:01:50.218 [error] <0.486.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.572.0>,1,<0.573.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 17:57:36.831 [error] <0.584.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"CENTER>\n<HR>\n<a href=\"http://somegreatsite.com\">Link Name</a>\nis a link to another nifty site\n<H1>This is a Header</H1>\n<H2>This is a Medium Header</H2>\nSend me mail at <a href=\"mailto:support@yourcompany.com\">\nsupport@yourcompany.com</a>.\n<P> This is a new paragraph!\n<P> <B>This is a new paragraph!</B>\n<BR> <B><I>This is a new sentence without a paragraph break, in bold italics.</I></B>\n<HR>\n</BODY>\n</HTML>\n">>}
2018-02-16 17:59:24.539 [error] <0.589.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"ul>\n\n<!-- Main content -->\n<h1>My first styled page</h1>\n\n<p>Welcome to my styled page!\n\n<p>It lacks images, but at least it has style.\nAnd it has links, even if they don't go\nanywhere&hellip;\n\n<p>There should be more here, but I don't know\nwhat yet.\n\n<!-- Sign and date the page, it's only polite! -->\n<address>Made 5 April 2004<br>\n  by myself.</address>\n\n</body>\n</html>">>}
2018-02-16 17:59:41.099 [error] <0.591.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"ul>\n\n<!-- Main content -->\n<h1>My first styled page</h1>\n\n<p>Welcome to my styled page!\n\n<p>It lacks images, but at least it has style.\nAnd it has links, even if they don't go\nanywhere&hellip;\n\n<p>There should be more here, but I don't know\nwhat yet.\n\n<!-- Sign and date the page, it's only polite! -->\n<address>Made 5 April 2004<br>\n  by myself.</address>\n\n</body>\n</html>">>}
2018-02-16 17:59:53.709 [error] <0.593.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"ul>\n\n<!-- Main content -->\n<h1>My first styled page</h1>\n\n<p>Welcome to my styled page!\n\n<p>It lacks images, but at least it has style.\nAnd it has links, even if they don't go\nanywhere&hellip;\n\n<p>There should be more here, but I don't know\nwhat yet.\n\n<!-- Sign and date the page, it's only polite! -->\n<address>Made 5 April 2004<br>\n  by myself.</address>\n\n</body>\n">>}
2018-02-16 17:59:59.933 [error] <0.595.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"ul>\n\n<!-- Main content -->\n<h1>My first styled page</h1>\n\n<p>Welcome to my styled page!\n\n<p>It lacks images, but at least it has style.\nAnd it has links, even if they don't go\nanywhere&hellip;\n\n<p>There should be more here, but I don't know\nwhat yet.\n\n\n</body>\n">>}
2018-02-16 18:00:35.717 [error] <0.597.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:00:41.561 [error] <0.600.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:22:25.204 [error] <0.582.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"html>">>}
2018-02-16 18:23:34.470 [error] <0.588.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"title>\n</head>\n<body>\n<p>dsadasdasd</p>\n<p>asdasdasdas</p>\n</body>\n</html>">>}
2018-02-16 18:24:26.322 [error] <0.594.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"title>\n</head>\n<body>\n<p>dsadasdasd<>\n<p>asdasdasdas</p>\n</body>\n</html>">>}
2018-02-16 18:24:31.295 [error] <0.595.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:26:30.278 [error] <0.599.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:30:23.095 [error] <0.734.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:30:40.930 [error] <0.736.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:30:49.221 [error] <0.738.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:34:36.021 [error] <0.764.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"ul>\n\n<!-- Main content -->\n<h1>My first styled page</h1>\n\n<p>Welcome to my styled page!\n\n<p>It lacks images, but at least it has style.\nAnd it has links, even if they don't go\nanywhere&hellip;\n\n<p>There should be more here, but I don't know\nwhat yet.\n\n<!-- Sign and date the page, it's only polite! -->\n<address>Made 5 April 2004<br>\n  by myself.</address>\n\n</body>\n</html>">>}
2018-02-16 18:36:47.667 [error] <0.775.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:37:27.989 [error] <0.777.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 18:40:49.137 [error] <0.797.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"body>\n</html>\n">>}
2018-02-16 18:44:54.054 [error] <0.734.0>@log:error:15 {validate_check_valid_body} function_clause
2018-02-16 20:36:34.417 [error] <0.741.0>@jsx_parser:value:163 CRASH REPORT Process <0.741.0> with 0 neighbours crashed with reason: bad argument in jsx_parser:value/4 line 163
2018-02-16 20:36:34.419 [error] <0.636.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.740.0>,1,<0.741.0>,badarg,[{jsx_parser,value,4,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/jsx/src/jsx_parser.erl"},{line,163}]},{http_handler,make_resp,3,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,37}]},{http_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/http_handler.erl"},{line,13}]},{cowboy_handler,execute,...},...]]},...}}
2018-02-16 20:39:44.073 [error] <0.747.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"body>">>}
2018-02-16 20:41:32.696 [error] <0.758.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"p>\n<p>Add a link to your favorite <a href=\"http://www.dummies.com/\">Web site</a>.\nBreak up your page with a horizontal rule or two. </p>\n<hr>\n<p>Finally, link to <a href=\"page2.html\">another page</a> in your own Web site.</p>\n<!-- And add a copyright notice.-->\n<p>&#169; Wiley Publishing, 2011</p>\n</body>\n</html>">>}
2018-02-16 20:44:24.642 [error] <0.761.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"p>\n<p>Add a link to your favorite <a href=\"http://www.dummies.com/\">Web site</a>.\nBreak up your page with a horizontal rule or two. </p>\n<hr>\n<p>Finally, link to <a href=\"page2.html\">another page</a> in your own Web site.</p>\n<!-- And add a copyright notice.-->\n<p>&#169; Wiley Publishing, 2011</p>\n</body>\n</html>">>}
2018-02-16 20:47:25.018 [error] <0.765.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"head>\n\n<body>\nContent of the document......\n</body>\n\n</html>">>}
2018-02-16 20:48:45.122 [error] <0.770.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"head>\n\n<body>\nContent of the document......\n\n\n</html>">>}
2018-02-16 20:49:27.133 [error] <0.775.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"head>\n\n<body>\nContent of the document......\n</body>\n\n</html>">>}
2018-02-16 20:49:46.272 [error] <0.777.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"head\n\n</html>">>}
2018-02-16 20:51:30.864 [error] <0.786.0>@log:error:15 {validate_check_valid_body} {badmatch,<<"head\n\n</html>">>}
2018-02-16 20:52:32.013 [error] <0.794.0>@log:error:15 {validate_check_valid_body} {badmatch,nomatch}
2018-02-16 20:54:10.231 [error] <0.800.0>@jiffy:encode CRASH REPORT Process <0.800.0> with 0 neighbours crashed with reason: call to undefined function jiffy:encode({invalid_validate,#{<<"reason">> => <<"incorrect path">>,<<"result">> => <<"error">>}})
2018-02-16 20:54:10.232 [error] <0.636.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[http,<0.799.0>,1,<0.800.0>,undef,[{jiffy,encode,[{invalid_validate,#{<<"reason">> => <<"incorrect path">>,<<"result">> => <<"error">>}}],[]},{not_found_handler,init,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/test_project/src/handlers/not_found_handler.erl"},{line,13}]},{cowboy_handler,execute,2,[{file,"/Users/vkutovoi/Documents/test_project/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,37}]},{cowboy_stream_h,execute,3,[{file,"/User..."},...]},...]]},...}}
2018-02-16 20:54:43.830 [error] <0.803.0>@log:error:15 {validate_check_valid_body} function_clause
